### ISSUE TITLE
timeoutの実装？

### ISSUE THREAD

**Issue by conan1024hao** [ku-nlp/rhoknp#151]
pyknpのjumanクラスでは[timeoutが実装されている](https://github.com/ku-nlp/pyknp/blob/52efc6805b2f251173e4dbb6d6a20925f110ef51/pyknp/juman/juman.py#L34)が、rhoknpはまだでしょうか？巨大なcsvファイルに対しjumanppを掛けようとしていて、途中でスタックしてしまいます(エラーメッセージは出ません)。timeoutがないとうまく対応できる方法が思いつきません。

**Comment by ogis-uno** [comment]
横から失礼します。原因同じかどうかわかりませんが、transformers 経由で jumanpp を使っていて同じような状態に。

以下、再現コードです。
Colab の環境がアップデートしたせいか、本日(2023/8/21)時点では以下の手順はビルドエラーになりますが、
`pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime` でコンテナ作ってもらえると再現可能だと思います。

https://huggingface.co/nlp-waseda/roberta-large-japanese-with-auto-jumanpp/discussions/2

Ctrl+C で止めると以下のようになり、
どうも jumanpp の標準出力を読もうとするけれど、何も出てこなくて待ち状態ということみたいです。
```
^CTraceback (most recent call last):
  File "./juman.py", line 20, in <module>
    features = tokenizer.batch_encode_plus(articles[-100:], padding="max_length", truncation=True, max_length=512)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2855, in batch_encode_plus
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 733, in _batch_encode_plus
    first_ids = get_input_ids(ids)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 700, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 547, in tokenize
    tokenized_text.extend(self._tokenize(token))
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/bert_japanese/tokenization_bert_japanese.py", line 264, in _tokenize
    tokens = self.word_tokenizer.tokenize(text, never_split=self.all_special_tokens)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/bert_japanese/tokenization_bert_japanese.py", line 669, in tokenize
    for mrph in self.juman.apply_to_sentence(text).morphemes:
  File "/opt/conda/lib/python3.7/site-packages/rhoknp/processors/jumanpp.py", line 124, in apply_to_sentence
    line = self._proc.stdout.readline()
```

**Comment by hkiyomaru** [comment]
ご報告ありがとうございます．近日中に対応予定です．

**Comment by nobu-g** [comment]
@conan1024hao @ogis-uno timeout を実装した rhoknp v1.5.0 をリリースしました．
また v1.5.0 では rhoknp の
